///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace UAT2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the UAT2Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("9505266f-6035-48d9-adbe-ca340c1d2ea7")]
    public partial class UAT2Repository : RepoGenBaseFolder
    {
        static UAT2Repository instance = new UAT2Repository();
        UAT2RepositoryFolders.SkySuiteAppFolder _skysuite;
        UAT2RepositoryFolders.ExportScheduleAppFolder _exportschedule;
        UAT2RepositoryFolders.SkySuiteEasyJetUAT2AppFolder _skysuiteeasyjetuat2;

        /// <summary>
        /// Gets the singleton class instance representing the UAT2Repository element repository.
        /// </summary>
        [RepositoryFolder("9505266f-6035-48d9-adbe-ca340c1d2ea7")]
        public static UAT2Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public UAT2Repository() 
            : base("UAT2Repository", "/", null, 0, false, "9505266f-6035-48d9-adbe-ca340c1d2ea7", ".\\RepositoryImages\\UAT2Repository9505266f.rximgres")
        {
            _skysuite = new UAT2RepositoryFolders.SkySuiteAppFolder(this);
            _exportschedule = new UAT2RepositoryFolders.ExportScheduleAppFolder(this);
            _skysuiteeasyjetuat2 = new UAT2RepositoryFolders.SkySuiteEasyJetUAT2AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("9505266f-6035-48d9-adbe-ca340c1d2ea7")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The SkySuite folder.
        /// </summary>
        [RepositoryFolder("73143b3f-e210-402c-89d6-cacdb456f339")]
        public virtual UAT2RepositoryFolders.SkySuiteAppFolder SkySuite
        {
            get { return _skysuite; }
        }

        /// <summary>
        /// The ExportSchedule folder.
        /// </summary>
        [RepositoryFolder("9d8380f3-54b7-4ec0-afb6-f9b829a82aad")]
        public virtual UAT2RepositoryFolders.ExportScheduleAppFolder ExportSchedule
        {
            get { return _exportschedule; }
        }

        /// <summary>
        /// The SkySuiteEasyJetUAT2 folder.
        /// </summary>
        [RepositoryFolder("51f914af-50b0-4f0e-9e91-a5f25f59168c")]
        public virtual UAT2RepositoryFolders.SkySuiteEasyJetUAT2AppFolder SkySuiteEasyJetUAT2
        {
            get { return _skysuiteeasyjetuat2; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class UAT2RepositoryFolders
    {
        /// <summary>
        /// The SkySuiteAppFolder folder.
        /// </summary>
        [RepositoryFolder("73143b3f-e210-402c-89d6-cacdb456f339")]
        public partial class SkySuiteAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _schedulesInfo;
            RepoItemInfo _schedulestabtoolbarssimexportbuttonInfo;
            RepoItemInfo _notificationsInfo;

            /// <summary>
            /// Creates a new SkySuite  folder.
            /// </summary>
            public SkySuiteAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SkySuite", "/form[@name='Root']", parentFolder, 30000, null, false, "73143b3f-e210-402c-89d6-cacdb456f339", "")
            {
                _schedulesInfo = new RepoItemInfo(this, "ScheduLes", ".//tabpagelist[@automationid='workbenchTabControl']//text[@caption='Schedu_les']", ".//tabpagelist[@automationid='workbenchTabControl']/container[@automationid='HeaderPanel']/tabpage[@title='Schedu_les']/text[@caption='Schedu_les']", 30000, null, "3f0d6ef8-8e47-4c10-a4d9-a31c7170de9c");
                _schedulestabtoolbarssimexportbuttonInfo = new RepoItemInfo(this, "SchedulesTabToolbarSSIMExportButton", ".//toolbar[@automationid='SchedulesTabToolbar']/button[@automationid='SchedulesTabToolbar_SSIMExportButton']", ".//button[@automationid='SchedulesTabToolbar_SSIMExportButton']", 30000, null, "2214a82d-e343-40b2-84e2-51dd4b06cc9d");
                _notificationsInfo = new RepoItemInfo(this, "Notifications", "container[@automationid='content']//button[@automationid='PART_Toggle']", "?/?/container[@caption='TitleBar']/container[@caption='']/button[@automationid='PART_Toggle']", 30000, null, "6a261917-bf27-4bef-9bc5-8ce4816f24d6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("73143b3f-e210-402c-89d6-cacdb456f339")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("73143b3f-e210-402c-89d6-cacdb456f339")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ScheduLes item.
            /// </summary>
            [RepositoryItem("3f0d6ef8-8e47-4c10-a4d9-a31c7170de9c")]
            public virtual Ranorex.Text ScheduLes
            {
                get
                {
                    return _schedulesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ScheduLes item info.
            /// </summary>
            [RepositoryItemInfo("3f0d6ef8-8e47-4c10-a4d9-a31c7170de9c")]
            public virtual RepoItemInfo ScheduLesInfo
            {
                get
                {
                    return _schedulesInfo;
                }
            }

            /// <summary>
            /// The SchedulesTabToolbarSSIMExportButton item.
            /// </summary>
            [RepositoryItem("2214a82d-e343-40b2-84e2-51dd4b06cc9d")]
            public virtual Ranorex.Button SchedulesTabToolbarSSIMExportButton
            {
                get
                {
                    return _schedulestabtoolbarssimexportbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SchedulesTabToolbarSSIMExportButton item info.
            /// </summary>
            [RepositoryItemInfo("2214a82d-e343-40b2-84e2-51dd4b06cc9d")]
            public virtual RepoItemInfo SchedulesTabToolbarSSIMExportButtonInfo
            {
                get
                {
                    return _schedulestabtoolbarssimexportbuttonInfo;
                }
            }

            /// <summary>
            /// The Notifications item.
            /// </summary>
            [RepositoryItem("6a261917-bf27-4bef-9bc5-8ce4816f24d6")]
            public virtual Ranorex.Button Notifications
            {
                get
                {
                    return _notificationsInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Notifications item info.
            /// </summary>
            [RepositoryItemInfo("6a261917-bf27-4bef-9bc5-8ce4816f24d6")]
            public virtual RepoItemInfo NotificationsInfo
            {
                get
                {
                    return _notificationsInfo;
                }
            }
        }

        /// <summary>
        /// The ExportScheduleAppFolder folder.
        /// </summary>
        [RepositoryFolder("9d8380f3-54b7-4ec0-afb6-f9b829a82aad")]
        public partial class ExportScheduleAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _exportInfo;

            /// <summary>
            /// Creates a new ExportSchedule  folder.
            /// </summary>
            public ExportScheduleAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ExportSchedule", "/form[@title='Export Schedule']", parentFolder, 30000, null, false, "9d8380f3-54b7-4ec0-afb6-f9b829a82aad", "")
            {
                _exportInfo = new RepoItemInfo(this, "Export", "container[@automationid='Footer']//text[@caption='Export']", ".//text[@caption='Export']", 30000, null, "3284ebc1-0f03-4717-aa2f-a662eb0bd4d5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9d8380f3-54b7-4ec0-afb6-f9b829a82aad")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9d8380f3-54b7-4ec0-afb6-f9b829a82aad")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Export item.
            /// </summary>
            [RepositoryItem("3284ebc1-0f03-4717-aa2f-a662eb0bd4d5")]
            public virtual Ranorex.Text Export
            {
                get
                {
                    return _exportInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Export item info.
            /// </summary>
            [RepositoryItemInfo("3284ebc1-0f03-4717-aa2f-a662eb0bd4d5")]
            public virtual RepoItemInfo ExportInfo
            {
                get
                {
                    return _exportInfo;
                }
            }
        }

        /// <summary>
        /// The SkySuiteEasyJetUAT2AppFolder folder.
        /// </summary>
        [RepositoryFolder("51f914af-50b0-4f0e-9e91-a5f25f59168c")]
        public partial class SkySuiteEasyJetUAT2AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _notification_itemInfo;

            /// <summary>
            /// Creates a new SkySuiteEasyJetUAT2  folder.
            /// </summary>
            public SkySuiteEasyJetUAT2AppFolder(RepoGenBaseFolder parentFolder) :
                    base("SkySuiteEasyJetUAT2", "/contextmenu[@processname='Sky.Suite.EasyJet UAT2']", parentFolder, 30000, null, false, "51f914af-50b0-4f0e-9e91-a5f25f59168c", "")
            {
                _notification_itemInfo = new RepoItemInfo(this, "Notification_Item", "?/?/list[@automationid='notificationsList']/listitem[@index='0']", "", 30000, null, "f5d4a0a1-b7ab-46bb-ad44-1c3ab4c0b410");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("51f914af-50b0-4f0e-9e91-a5f25f59168c")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("51f914af-50b0-4f0e-9e91-a5f25f59168c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Notification_Item item.
            /// </summary>
            [RepositoryItem("f5d4a0a1-b7ab-46bb-ad44-1c3ab4c0b410")]
            public virtual Ranorex.ListItem Notification_Item
            {
                get
                {
                    return _notification_itemInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Notification_Item item info.
            /// </summary>
            [RepositoryItemInfo("f5d4a0a1-b7ab-46bb-ad44-1c3ab4c0b410")]
            public virtual RepoItemInfo Notification_ItemInfo
            {
                get
                {
                    return _notification_itemInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
