///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace UAT2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the UAT2Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("9505266f-6035-48d9-adbe-ca340c1d2ea7")]
    public partial class UAT2Repository : RepoGenBaseFolder
    {
        static UAT2Repository instance = new UAT2Repository();
        UAT2RepositoryFolders.SkySuiteAppFolder _skysuite;
        UAT2RepositoryFolders.ExportScheduleAppFolder _exportschedule;
        UAT2RepositoryFolders.SkySuiteEasyJetUAT2AppFolder _skysuiteeasyjetuat2;
        UAT2RepositoryFolders.JobWindowAppFolder _jobwindow;

        /// <summary>
        /// Gets the singleton class instance representing the UAT2Repository element repository.
        /// </summary>
        [RepositoryFolder("9505266f-6035-48d9-adbe-ca340c1d2ea7")]
        public static UAT2Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public UAT2Repository() 
            : base("UAT2Repository", "/", null, 0, false, "9505266f-6035-48d9-adbe-ca340c1d2ea7", ".\\RepositoryImages\\UAT2Repository9505266f.rximgres")
        {
            _skysuite = new UAT2RepositoryFolders.SkySuiteAppFolder(this);
            _exportschedule = new UAT2RepositoryFolders.ExportScheduleAppFolder(this);
            _skysuiteeasyjetuat2 = new UAT2RepositoryFolders.SkySuiteEasyJetUAT2AppFolder(this);
            _jobwindow = new UAT2RepositoryFolders.JobWindowAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("9505266f-6035-48d9-adbe-ca340c1d2ea7")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The SkySuite folder.
        /// </summary>
        [RepositoryFolder("73143b3f-e210-402c-89d6-cacdb456f339")]
        public virtual UAT2RepositoryFolders.SkySuiteAppFolder SkySuite
        {
            get { return _skysuite; }
        }

        /// <summary>
        /// The ExportSchedule folder.
        /// </summary>
        [RepositoryFolder("9d8380f3-54b7-4ec0-afb6-f9b829a82aad")]
        public virtual UAT2RepositoryFolders.ExportScheduleAppFolder ExportSchedule
        {
            get { return _exportschedule; }
        }

        /// <summary>
        /// The SkySuiteEasyJetUAT2 folder.
        /// </summary>
        [RepositoryFolder("51f914af-50b0-4f0e-9e91-a5f25f59168c")]
        public virtual UAT2RepositoryFolders.SkySuiteEasyJetUAT2AppFolder SkySuiteEasyJetUAT2
        {
            get { return _skysuiteeasyjetuat2; }
        }

        /// <summary>
        /// The JobWindow folder.
        /// </summary>
        [RepositoryFolder("b98a70ba-2c3b-491e-96af-a80fd0669a29")]
        public virtual UAT2RepositoryFolders.JobWindowAppFolder JobWindow
        {
            get { return _jobwindow; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class UAT2RepositoryFolders
    {
        /// <summary>
        /// The SkySuiteAppFolder folder.
        /// </summary>
        [RepositoryFolder("73143b3f-e210-402c-89d6-cacdb456f339")]
        public partial class SkySuiteAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _schedulesInfo;
            RepoItemInfo _schedulestabtoolbarssimexportbuttonInfo;
            RepoItemInfo _notificationsInfo;

            /// <summary>
            /// Creates a new SkySuite  folder.
            /// </summary>
            public SkySuiteAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SkySuite", "/form[@name='Root']", parentFolder, 30000, null, false, "73143b3f-e210-402c-89d6-cacdb456f339", "")
            {
                _schedulesInfo = new RepoItemInfo(this, "ScheduLes", ".//tabpagelist[@automationid='workbenchTabControl']//text[@caption='Schedu_les']", ".//tabpagelist[@automationid='workbenchTabControl']/container[@automationid='HeaderPanel']/tabpage[@title='Schedu_les']/text[@caption='Schedu_les']", 30000, null, "3f0d6ef8-8e47-4c10-a4d9-a31c7170de9c");
                _schedulestabtoolbarssimexportbuttonInfo = new RepoItemInfo(this, "SchedulesTabToolbarSSIMExportButton", ".//toolbar[@automationid='SchedulesTabToolbar']/button[@automationid='SchedulesTabToolbar_SSIMExportButton']", ".//button[@automationid='SchedulesTabToolbar_SSIMExportButton']", 30000, null, "2214a82d-e343-40b2-84e2-51dd4b06cc9d");
                _notificationsInfo = new RepoItemInfo(this, "Notifications", "container[@automationid='content']//button[@automationid='PART_Toggle']", "?/?/container[@caption='TitleBar']/container[@caption='']/button[@automationid='PART_Toggle']", 30000, null, "6a261917-bf27-4bef-9bc5-8ce4816f24d6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("73143b3f-e210-402c-89d6-cacdb456f339")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("73143b3f-e210-402c-89d6-cacdb456f339")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ScheduLes item.
            /// </summary>
            [RepositoryItem("3f0d6ef8-8e47-4c10-a4d9-a31c7170de9c")]
            public virtual Ranorex.Text ScheduLes
            {
                get
                {
                    return _schedulesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ScheduLes item info.
            /// </summary>
            [RepositoryItemInfo("3f0d6ef8-8e47-4c10-a4d9-a31c7170de9c")]
            public virtual RepoItemInfo ScheduLesInfo
            {
                get
                {
                    return _schedulesInfo;
                }
            }

            /// <summary>
            /// The SchedulesTabToolbarSSIMExportButton item.
            /// </summary>
            [RepositoryItem("2214a82d-e343-40b2-84e2-51dd4b06cc9d")]
            public virtual Ranorex.Button SchedulesTabToolbarSSIMExportButton
            {
                get
                {
                    return _schedulestabtoolbarssimexportbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SchedulesTabToolbarSSIMExportButton item info.
            /// </summary>
            [RepositoryItemInfo("2214a82d-e343-40b2-84e2-51dd4b06cc9d")]
            public virtual RepoItemInfo SchedulesTabToolbarSSIMExportButtonInfo
            {
                get
                {
                    return _schedulestabtoolbarssimexportbuttonInfo;
                }
            }

            /// <summary>
            /// The Notifications item.
            /// </summary>
            [RepositoryItem("6a261917-bf27-4bef-9bc5-8ce4816f24d6")]
            public virtual Ranorex.Button Notifications
            {
                get
                {
                    return _notificationsInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Notifications item info.
            /// </summary>
            [RepositoryItemInfo("6a261917-bf27-4bef-9bc5-8ce4816f24d6")]
            public virtual RepoItemInfo NotificationsInfo
            {
                get
                {
                    return _notificationsInfo;
                }
            }
        }

        /// <summary>
        /// The ExportScheduleAppFolder folder.
        /// </summary>
        [RepositoryFolder("9d8380f3-54b7-4ec0-afb6-f9b829a82aad")]
        public partial class ExportScheduleAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _exportInfo;

            /// <summary>
            /// Creates a new ExportSchedule  folder.
            /// </summary>
            public ExportScheduleAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ExportSchedule", "/form[@title='Export Schedule']", parentFolder, 30000, null, false, "9d8380f3-54b7-4ec0-afb6-f9b829a82aad", "")
            {
                _exportInfo = new RepoItemInfo(this, "Export", "container[@automationid='Footer']//text[@caption='Export']", ".//text[@caption='Export']", 30000, null, "3284ebc1-0f03-4717-aa2f-a662eb0bd4d5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9d8380f3-54b7-4ec0-afb6-f9b829a82aad")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9d8380f3-54b7-4ec0-afb6-f9b829a82aad")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Export item.
            /// </summary>
            [RepositoryItem("3284ebc1-0f03-4717-aa2f-a662eb0bd4d5")]
            public virtual Ranorex.Text Export
            {
                get
                {
                    return _exportInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Export item info.
            /// </summary>
            [RepositoryItemInfo("3284ebc1-0f03-4717-aa2f-a662eb0bd4d5")]
            public virtual RepoItemInfo ExportInfo
            {
                get
                {
                    return _exportInfo;
                }
            }
        }

        /// <summary>
        /// The SkySuiteEasyJetUAT2AppFolder folder.
        /// </summary>
        [RepositoryFolder("51f914af-50b0-4f0e-9e91-a5f25f59168c")]
        public partial class SkySuiteEasyJetUAT2AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _notification_itemInfo;

            /// <summary>
            /// Creates a new SkySuiteEasyJetUAT2  folder.
            /// </summary>
            public SkySuiteEasyJetUAT2AppFolder(RepoGenBaseFolder parentFolder) :
                    base("SkySuiteEasyJetUAT2", "/contextmenu[@processname='Sky.Suite.EasyJet UAT2']", parentFolder, 30000, null, false, "51f914af-50b0-4f0e-9e91-a5f25f59168c", "")
            {
                _notification_itemInfo = new RepoItemInfo(this, "Notification_Item", "?/?/list[@automationid='notificationsList']/listitem[@index='0']", "", 30000, null, "f5d4a0a1-b7ab-46bb-ad44-1c3ab4c0b410");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("51f914af-50b0-4f0e-9e91-a5f25f59168c")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("51f914af-50b0-4f0e-9e91-a5f25f59168c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Notification_Item item.
            /// </summary>
            [RepositoryItem("f5d4a0a1-b7ab-46bb-ad44-1c3ab4c0b410")]
            public virtual Ranorex.ListItem Notification_Item
            {
                get
                {
                    return _notification_itemInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Notification_Item item info.
            /// </summary>
            [RepositoryItemInfo("f5d4a0a1-b7ab-46bb-ad44-1c3ab4c0b410")]
            public virtual RepoItemInfo Notification_ItemInfo
            {
                get
                {
                    return _notification_itemInfo;
                }
            }
        }

        /// <summary>
        /// The JobWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("b98a70ba-2c3b-491e-96af-a80fd0669a29")]
        public partial class JobWindowAppFolder : RepoGenBaseFolder
        {
            UAT2RepositoryFolders.Report_TabFolder _report_tab;
            RepoItemInfo _close_windowInfo;
            RepoItemInfo _flight_expandInfo;
            RepoItemInfo _flight_countInfo;
            RepoItemInfo _flight_count_rowInfo;
            RepoItemInfo _traffic_expandInfo;
            RepoItemInfo _trafficInfo;
            RepoItemInfo _traffic_rowInfo;

            /// <summary>
            /// Creates a new JobWindow  folder.
            /// </summary>
            public JobWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("JobWindow", "/form[@name='Root' and @title~'Jobs']", parentFolder, 30000, null, false, "b98a70ba-2c3b-491e-96af-a80fd0669a29", "")
            {
                _report_tab = new UAT2RepositoryFolders.Report_TabFolder(this);
                _close_windowInfo = new RepoItemInfo(this, "Close_Window", "?/?/button[@automationid='PART_CloseButton']", "?/button[@automationid='PART_CloseButton']", 30000, null, "2a8d4ac5-bacf-459f-bb54-13a533c31e5b");
                _flight_expandInfo = new RepoItemInfo(this, "Flight_Expand", ".//button[@automationid='PART_HeaderExpander']/table[@automationid='KpiListView']/container[@automationid='PART_ItemsScrollViewer']/container[@automationid='PART_GridViewVirtualizingPanel']/row[2]/button[@automationid='PART_ExpandButton']", ".//container[@automationid='PART_GridViewVirtualizingPanel']/row[2]/button[@automationid='PART_ExpandButton']", 30000, null, "2858bf1c-9213-470a-b604-f7d635297ba5");
                _flight_countInfo = new RepoItemInfo(this, "Flight_Count", ".//button[@automationid='PART_HeaderExpander']/table[@automationid='KpiListView']/container[@automationid='PART_ItemsScrollViewer']/container[@automationid='PART_GridViewVirtualizingPanel']/row[3]/list[@automationid='PART_DataCellsPresenter']/?/?/text[@caption='Flight Count - Schedule']", ".//button[@automationid='PART_HeaderExpander']/table[@automationid='KpiListView']/container[@automationid='PART_ItemsScrollViewer']/container[@automationid='PART_GridViewVirtualizingPanel']", 30000, null, "c93729ed-9097-46ce-b88d-11e69bb1b49c");
                _flight_count_rowInfo = new RepoItemInfo(this, "Flight_Count_Row", ".//button[@automationid='PART_HeaderExpander']/table[@automationid='KpiListView']/container[@automationid='PART_ItemsScrollViewer']/container[@automationid='PART_GridViewVirtualizingPanel']/row[3]", ".//button[@automationid='PART_HeaderExpander']/table[@automationid='KpiListView']/container[@automationid='PART_ItemsScrollViewer']/container[@automationid='PART_GridViewVirtualizingPanel']", 30000, null, "66ebd1ec-e6b9-4a8d-8189-d6ec8bcbabec");
                _traffic_expandInfo = new RepoItemInfo(this, "Traffic_Expand", ".//button[@automationid='PART_HeaderExpander']/table[@automationid='KpiListView']/container[@automationid='PART_ItemsScrollViewer']/container[@automationid='PART_GridViewVirtualizingPanel']/row[11]/button[@automationid='PART_ExpandButton']", ".//container[@automationid='PART_GridViewVirtualizingPanel']/row[11]/button[@automationid='PART_ExpandButton']", 30000, null, "7f985451-94c0-4c52-94d5-a3dca45fca2b");
                _trafficInfo = new RepoItemInfo(this, "Traffic", ".//button[@automationid='PART_HeaderExpander']/table[@automationid='KpiListView']/container[@automationid='PART_ItemsScrollViewer']/container[@automationid='PART_GridViewVirtualizingPanel']/row[13]/list[@automationid='PART_DataCellsPresenter']/?/?/text[@caption='Traffic']", ".//container[@automationid='PART_GridViewVirtualizingPanel']/row[13]/list[@automationid='PART_DataCellsPresenter']/cell[1]/text[@caption='Traffic']", 30000, null, "3c6e75db-1a88-4516-a6b9-746500eaf85b");
                _traffic_rowInfo = new RepoItemInfo(this, "Traffic_Row", ".//button[@automationid='PART_HeaderExpander']/table[@automationid='KpiListView']/container[@automationid='PART_ItemsScrollViewer']/container[@automationid='PART_GridViewVirtualizingPanel']/row[13]", ".//container[@automationid='PART_GridViewVirtualizingPanel']/row[13]/list[@automationid='PART_DataCellsPresenter']/cell[1]/text[@caption='Traffic']", 30000, null, "68dfaadb-9655-446e-ad38-414cbcbb9449");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b98a70ba-2c3b-491e-96af-a80fd0669a29")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b98a70ba-2c3b-491e-96af-a80fd0669a29")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close_Window item.
            /// </summary>
            [RepositoryItem("2a8d4ac5-bacf-459f-bb54-13a533c31e5b")]
            public virtual Ranorex.Button Close_Window
            {
                get
                {
                    return _close_windowInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close_Window item info.
            /// </summary>
            [RepositoryItemInfo("2a8d4ac5-bacf-459f-bb54-13a533c31e5b")]
            public virtual RepoItemInfo Close_WindowInfo
            {
                get
                {
                    return _close_windowInfo;
                }
            }

            /// <summary>
            /// The Flight_Expand item.
            /// </summary>
            [RepositoryItem("2858bf1c-9213-470a-b604-f7d635297ba5")]
            public virtual Ranorex.Button Flight_Expand
            {
                get
                {
                    return _flight_expandInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Flight_Expand item info.
            /// </summary>
            [RepositoryItemInfo("2858bf1c-9213-470a-b604-f7d635297ba5")]
            public virtual RepoItemInfo Flight_ExpandInfo
            {
                get
                {
                    return _flight_expandInfo;
                }
            }

            /// <summary>
            /// The Flight_Count item.
            /// </summary>
            [RepositoryItem("c93729ed-9097-46ce-b88d-11e69bb1b49c")]
            public virtual Ranorex.Text Flight_Count
            {
                get
                {
                    return _flight_countInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Flight_Count item info.
            /// </summary>
            [RepositoryItemInfo("c93729ed-9097-46ce-b88d-11e69bb1b49c")]
            public virtual RepoItemInfo Flight_CountInfo
            {
                get
                {
                    return _flight_countInfo;
                }
            }

            /// <summary>
            /// The Flight_Count_Row item.
            /// </summary>
            [RepositoryItem("66ebd1ec-e6b9-4a8d-8189-d6ec8bcbabec")]
            public virtual Ranorex.Row Flight_Count_Row
            {
                get
                {
                    return _flight_count_rowInfo.CreateAdapter<Ranorex.Row>(true);
                }
            }

            /// <summary>
            /// The Flight_Count_Row item info.
            /// </summary>
            [RepositoryItemInfo("66ebd1ec-e6b9-4a8d-8189-d6ec8bcbabec")]
            public virtual RepoItemInfo Flight_Count_RowInfo
            {
                get
                {
                    return _flight_count_rowInfo;
                }
            }

            /// <summary>
            /// The Traffic_Expand item.
            /// </summary>
            [RepositoryItem("7f985451-94c0-4c52-94d5-a3dca45fca2b")]
            public virtual Ranorex.Button Traffic_Expand
            {
                get
                {
                    return _traffic_expandInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Traffic_Expand item info.
            /// </summary>
            [RepositoryItemInfo("7f985451-94c0-4c52-94d5-a3dca45fca2b")]
            public virtual RepoItemInfo Traffic_ExpandInfo
            {
                get
                {
                    return _traffic_expandInfo;
                }
            }

            /// <summary>
            /// The Traffic item.
            /// </summary>
            [RepositoryItem("3c6e75db-1a88-4516-a6b9-746500eaf85b")]
            public virtual Ranorex.Text Traffic
            {
                get
                {
                    return _trafficInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Traffic item info.
            /// </summary>
            [RepositoryItemInfo("3c6e75db-1a88-4516-a6b9-746500eaf85b")]
            public virtual RepoItemInfo TrafficInfo
            {
                get
                {
                    return _trafficInfo;
                }
            }

            /// <summary>
            /// The Traffic_Row item.
            /// </summary>
            [RepositoryItem("68dfaadb-9655-446e-ad38-414cbcbb9449")]
            public virtual Ranorex.Row Traffic_Row
            {
                get
                {
                    return _traffic_rowInfo.CreateAdapter<Ranorex.Row>(true);
                }
            }

            /// <summary>
            /// The Traffic_Row item info.
            /// </summary>
            [RepositoryItemInfo("68dfaadb-9655-446e-ad38-414cbcbb9449")]
            public virtual RepoItemInfo Traffic_RowInfo
            {
                get
                {
                    return _traffic_rowInfo;
                }
            }

            /// <summary>
            /// The Report_Tab folder.
            /// </summary>
            [RepositoryFolder("b334a0cc-dfa8-441b-aaba-09b6b6f8f9ac")]
            public virtual UAT2RepositoryFolders.Report_TabFolder Report_Tab
            {
                get { return _report_tab; }
            }
        }

        /// <summary>
        /// The Report_TabFolder folder.
        /// </summary>
        [RepositoryFolder("b334a0cc-dfa8-441b-aaba-09b6b6f8f9ac")]
        public partial class Report_TabFolder : RepoGenBaseFolder
        {
            UAT2RepositoryFolders.Forcast_Report_MetricsFolder _forcast_report_metrics;
            Report_PageInfoClass _report_pageInfo;

            /// <summary>
            /// Creates a new Report_Tab  folder.
            /// </summary>
            public Report_TabFolder(RepoGenBaseFolder parentFolder) :
                    base("Report_Tab", "", parentFolder, 0, null, false, "b334a0cc-dfa8-441b-aaba-09b6b6f8f9ac", "")
            {
                _forcast_report_metrics = new UAT2RepositoryFolders.Forcast_Report_MetricsFolder(this);
                _report_pageInfo = new Report_PageInfoClass(this);
            }

            /// <summary>
            /// The Report_PageInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("f0ab2441-6923-4bdc-8cc1-11748a3f59dc")]
            public class Report_PageInfoClass : RepoItemInfo
            {
                /// <summary>
                /// Report_PageInfoClass class constructor.
                /// </summary>
                public Report_PageInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Report_Page", "indicator", 30000, null, "f0ab2441-6923-4bdc-8cc1-11748a3f59dc")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("2f301309-82e4-4cd9-8d9a-3b169438dc59")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("2f301309-82e4-4cd9-8d9a-3b169438dc59");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("2f301309-82e4-4cd9-8d9a-3b169438dc59")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("2f301309-82e4-4cd9-8d9a-3b169438dc59", cropRect);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b334a0cc-dfa8-441b-aaba-09b6b6f8f9ac")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Report_Page item.
            /// </summary>
            [RepositoryItem("f0ab2441-6923-4bdc-8cc1-11748a3f59dc")]
            public virtual Ranorex.Indicator Report_Page
            {
                get
                {
                    return _report_pageInfo.CreateAdapter<Ranorex.Indicator>(true);
                }
            }

            /// <summary>
            /// The Report_Page item info.
            /// </summary>
            [RepositoryItemInfo("f0ab2441-6923-4bdc-8cc1-11748a3f59dc")]
            public virtual Report_PageInfoClass Report_PageInfo
            {
                get
                {
                    return _report_pageInfo;
                }
            }

            /// <summary>
            /// The Forcast_Report_Metrics folder.
            /// </summary>
            [RepositoryFolder("2c210d6e-df41-4da5-a313-313c430542e8")]
            public virtual UAT2RepositoryFolders.Forcast_Report_MetricsFolder Forcast_Report_Metrics
            {
                get { return _forcast_report_metrics; }
            }
        }

        /// <summary>
        /// The Forcast_Report_MetricsFolder folder.
        /// </summary>
        [RepositoryFolder("2c210d6e-df41-4da5-a313-313c430542e8")]
        public partial class Forcast_Report_MetricsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _flight_expandInfo;
            RepoItemInfo _flight_countInfo;
            RepoItemInfo _flight_count_rowInfo;
            RepoItemInfo _traffic_expandInfo;
            RepoItemInfo _trafficInfo;
            RepoItemInfo _traffic_rowInfo;

            /// <summary>
            /// Creates a new Forcast_Report_Metrics  folder.
            /// </summary>
            public Forcast_Report_MetricsFolder(RepoGenBaseFolder parentFolder) :
                    base("Forcast_Report_Metrics", "", parentFolder, 0, null, false, "2c210d6e-df41-4da5-a313-313c430542e8", "")
            {
                _flight_expandInfo = new RepoItemInfo(this, "Flight_Expand", ".//button[@automationid='PART_HeaderExpander']/table[@automationid='KpiListView']/container[@automationid='PART_ItemsScrollViewer']/container[@automationid='PART_GridViewVirtualizingPanel']/row[2]/button[@automationid='PART_ExpandButton']", ".//container[@automationid='PART_GridViewVirtualizingPanel']/row[2]/button[@automationid='PART_ExpandButton']", 30000, null, "50aa56f5-81d8-4733-a1b1-fc51337452c2");
                _flight_countInfo = new RepoItemInfo(this, "Flight_Count", ".//button[@automationid='PART_HeaderExpander']/table[@automationid='KpiListView']/container[@automationid='PART_ItemsScrollViewer']/container[@automationid='PART_GridViewVirtualizingPanel']/row[3]/list[@automationid='PART_DataCellsPresenter']/?/?/text[@caption='Flight Count - Schedule']", ".//button[@automationid='PART_HeaderExpander']/table[@automationid='KpiListView']/container[@automationid='PART_ItemsScrollViewer']/container[@automationid='PART_GridViewVirtualizingPanel']", 30000, null, "aa903007-9de8-40c9-bd39-5f2d4a652564");
                _flight_count_rowInfo = new RepoItemInfo(this, "Flight_Count_Row", ".//button[@automationid='PART_HeaderExpander']/table[@automationid='KpiListView']/container[@automationid='PART_ItemsScrollViewer']/container[@automationid='PART_GridViewVirtualizingPanel']/row[3]", ".//button[@automationid='PART_HeaderExpander']/table[@automationid='KpiListView']/container[@automationid='PART_ItemsScrollViewer']/container[@automationid='PART_GridViewVirtualizingPanel']", 30000, null, "68ba51de-8dd2-415e-8e89-fbe67f5829ed");
                _traffic_expandInfo = new RepoItemInfo(this, "Traffic_Expand", ".//button[@automationid='PART_HeaderExpander']/table[@automationid='KpiListView']/container[@automationid='PART_ItemsScrollViewer']/container[@automationid='PART_GridViewVirtualizingPanel']/row[11]/button[@automationid='PART_ExpandButton']", ".//container[@automationid='PART_GridViewVirtualizingPanel']/row[11]/button[@automationid='PART_ExpandButton']", 30000, null, "65775857-ccb3-4b70-b4c3-c0cc934e7c5e");
                _trafficInfo = new RepoItemInfo(this, "Traffic", ".//button[@automationid='PART_HeaderExpander']/table[@automationid='KpiListView']/container[@automationid='PART_ItemsScrollViewer']/container[@automationid='PART_GridViewVirtualizingPanel']/row[13]/list[@automationid='PART_DataCellsPresenter']/?/?/text[@caption='Traffic']", ".//container[@automationid='PART_GridViewVirtualizingPanel']/row[13]/list[@automationid='PART_DataCellsPresenter']/cell[1]/text[@caption='Traffic']", 30000, null, "5562087c-d33a-4ed5-881d-91bd56674141");
                _traffic_rowInfo = new RepoItemInfo(this, "Traffic_Row", ".//button[@automationid='PART_HeaderExpander']/table[@automationid='KpiListView']/container[@automationid='PART_ItemsScrollViewer']/container[@automationid='PART_GridViewVirtualizingPanel']/row[13]", ".//container[@automationid='PART_GridViewVirtualizingPanel']/row[13]/list[@automationid='PART_DataCellsPresenter']/cell[1]/text[@caption='Traffic']", 30000, null, "8679fa66-be59-4b7d-a386-0ee1ea0df06e");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2c210d6e-df41-4da5-a313-313c430542e8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Flight_Expand item.
            /// </summary>
            [RepositoryItem("50aa56f5-81d8-4733-a1b1-fc51337452c2")]
            public virtual Ranorex.Button Flight_Expand
            {
                get
                {
                    return _flight_expandInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Flight_Expand item info.
            /// </summary>
            [RepositoryItemInfo("50aa56f5-81d8-4733-a1b1-fc51337452c2")]
            public virtual RepoItemInfo Flight_ExpandInfo
            {
                get
                {
                    return _flight_expandInfo;
                }
            }

            /// <summary>
            /// The Flight_Count item.
            /// </summary>
            [RepositoryItem("aa903007-9de8-40c9-bd39-5f2d4a652564")]
            public virtual Ranorex.Text Flight_Count
            {
                get
                {
                    return _flight_countInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Flight_Count item info.
            /// </summary>
            [RepositoryItemInfo("aa903007-9de8-40c9-bd39-5f2d4a652564")]
            public virtual RepoItemInfo Flight_CountInfo
            {
                get
                {
                    return _flight_countInfo;
                }
            }

            /// <summary>
            /// The Flight_Count_Row item.
            /// </summary>
            [RepositoryItem("68ba51de-8dd2-415e-8e89-fbe67f5829ed")]
            public virtual Ranorex.Row Flight_Count_Row
            {
                get
                {
                    return _flight_count_rowInfo.CreateAdapter<Ranorex.Row>(true);
                }
            }

            /// <summary>
            /// The Flight_Count_Row item info.
            /// </summary>
            [RepositoryItemInfo("68ba51de-8dd2-415e-8e89-fbe67f5829ed")]
            public virtual RepoItemInfo Flight_Count_RowInfo
            {
                get
                {
                    return _flight_count_rowInfo;
                }
            }

            /// <summary>
            /// The Traffic_Expand item.
            /// </summary>
            [RepositoryItem("65775857-ccb3-4b70-b4c3-c0cc934e7c5e")]
            public virtual Ranorex.Button Traffic_Expand
            {
                get
                {
                    return _traffic_expandInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Traffic_Expand item info.
            /// </summary>
            [RepositoryItemInfo("65775857-ccb3-4b70-b4c3-c0cc934e7c5e")]
            public virtual RepoItemInfo Traffic_ExpandInfo
            {
                get
                {
                    return _traffic_expandInfo;
                }
            }

            /// <summary>
            /// The Traffic item.
            /// </summary>
            [RepositoryItem("5562087c-d33a-4ed5-881d-91bd56674141")]
            public virtual Ranorex.Text Traffic
            {
                get
                {
                    return _trafficInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Traffic item info.
            /// </summary>
            [RepositoryItemInfo("5562087c-d33a-4ed5-881d-91bd56674141")]
            public virtual RepoItemInfo TrafficInfo
            {
                get
                {
                    return _trafficInfo;
                }
            }

            /// <summary>
            /// The Traffic_Row item.
            /// </summary>
            [RepositoryItem("8679fa66-be59-4b7d-a386-0ee1ea0df06e")]
            public virtual Ranorex.Row Traffic_Row
            {
                get
                {
                    return _traffic_rowInfo.CreateAdapter<Ranorex.Row>(true);
                }
            }

            /// <summary>
            /// The Traffic_Row item info.
            /// </summary>
            [RepositoryItemInfo("8679fa66-be59-4b7d-a386-0ee1ea0df06e")]
            public virtual RepoItemInfo Traffic_RowInfo
            {
                get
                {
                    return _traffic_rowInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
