///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AtlasAutomation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Duplicate_TC_04_6 recording.
    /// </summary>
    [TestModule("0a2398c0-c4b7-4f73-87a4-c23533c1e570", ModuleType.Recording, 1)]
    public partial class Duplicate_TC_04_6 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the AtlasAutomationRepository repository.
        /// </summary>
        public static AtlasAutomationRepository repo = AtlasAutomationRepository.Instance;

        static Duplicate_TC_04_6 instance = new Duplicate_TC_04_6();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Duplicate_TC_04_6()
        {
            Jb6_Name = "Eval_Low";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Duplicate_TC_04_6 Instance
        {
            get { return instance; }
        }

#region Variables

        string _Jb6_Name;

        /// <summary>
        /// Gets or sets the value of variable Jb6_Name.
        /// </summary>
        [TestVariable("5874f551-af5f-4b9f-ae88-3133b7be326c")]
        public string Jb6_Name
        {
            get { return _Jb6_Name; }
            set { _Jb6_Name = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SkySuite' at 1261;28.", repo.SkySuite.SelfInfo, new RecordItemIndex(0));
            repo.SkySuite.Self.Click("1261;28");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'SkySuite.Eval_med_2' at Center.", repo.SkySuite.Eval_med_2Info, new RecordItemIndex(1));
            repo.SkySuite.Eval_med_2.Click(System.Windows.Forms.MouseButtons.Right);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SkySuiteEasyJetUAT2.DUplicate1' at 18;7.", repo.SkySuiteEasyJetUAT2.DUplicate1Info, new RecordItemIndex(2));
            repo.SkySuiteEasyJetUAT2.DUplicate1.Click("18;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SkySuite.ScenarioTreeListView' at 558;222.", repo.SkySuite.ScenarioTreeListViewInfo, new RecordItemIndex(3));
            repo.SkySuite.ScenarioTreeListView.Click("558;222");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DuplicateJobToCurrentScenario' at 463;33.", repo.DuplicateJobToCurrentScenario.SelfInfo, new RecordItemIndex(4));
            repo.DuplicateJobToCurrentScenario.Self.Click("463;33");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.DuplicateJobToCurrentScenario.Self, false, new RecordItemIndex(5));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DuplicateJobToCurrentScenario' at 357;28.", repo.DuplicateJobToCurrentScenario.SelfInfo, new RecordItemIndex(6));
            repo.DuplicateJobToCurrentScenario.Self.Click("357;28");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(7));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DuplicateJobToCurrentScenario.Job_Name' at 285;9.", repo.DuplicateJobToCurrentScenario.Job_NameInfo, new RecordItemIndex(8));
            repo.DuplicateJobToCurrentScenario.Job_Name.Click("285;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back 60}' with focus on 'DuplicateJobToCurrentScenario.Job_Name'.", repo.DuplicateJobToCurrentScenario.Job_NameInfo, new RecordItemIndex(9));
            repo.DuplicateJobToCurrentScenario.Job_Name.PressKeys("{Back 60}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Jb6_Name' with focus on 'DuplicateJobToCurrentScenario.Job_Name'.", repo.DuplicateJobToCurrentScenario.Job_NameInfo, new RecordItemIndex(10));
            repo.DuplicateJobToCurrentScenario.Job_Name.PressKeys(Jb6_Name);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DuplicateJobToCurrentScenario.Create' at 23;10.", repo.DuplicateJobToCurrentScenario.CreateInfo, new RecordItemIndex(11));
            repo.DuplicateJobToCurrentScenario.Create.Click("23;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(12));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow' at Center.", repo.JobWindow.SelfInfo, new RecordItemIndex(13));
            repo.JobWindow.Self.Click();
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.JobWindow.Self, false, new RecordItemIndex(14));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow' at Center.", repo.JobWindow.SelfInfo, new RecordItemIndex(15));
            repo.JobWindow.Self.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
