///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AtlasAutomation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The FilloutScenarioDetails04 recording.
    /// </summary>
    [TestModule("30701a83-5693-489b-b9f5-b3336727caf4", ModuleType.Recording, 1)]
    public partial class CreateScenario4 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the AtlasAutomationRepository repository.
        /// </summary>
        public static AtlasAutomationRepository repo = AtlasAutomationRepository.Instance;

        static CreateScenario4 instance = new CreateScenario4();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CreateScenario4()
        {
            scNameEval = "Eval_Jobs";
            jb4Name = "TC_04";
            datesMed = "18Sep2023 to 24Sep2023";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CreateScenario4 Instance
        {
            get { return instance; }
        }

#region Variables

        string _scNameEval;

        /// <summary>
        /// Gets or sets the value of variable scNameEval.
        /// </summary>
        [TestVariable("94b96abf-dc8a-435a-a28e-d700655b8eee")]
        public string scNameEval
        {
            get { return _scNameEval; }
            set { _scNameEval = value; }
        }

        string _datesMed;

        /// <summary>
        /// Gets or sets the value of variable datesMed.
        /// </summary>
        [TestVariable("e6ea2878-77c9-4d66-9021-2d1ec622fb08")]
        public string datesMed
        {
            get { return _datesMed; }
            set { _datesMed = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable jb4Name.
        /// </summary>
        [TestVariable("146de5d7-b8e2-4d67-a246-24dd56921b4f")]
        public string jb4Name
        {
            get { return repo.jb4Name; }
            set { repo.jb4Name = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewScenario.SomeContainer.Scenario_Name' at CenterRight.", repo.NewScenario.SomeContainer.Scenario_NameInfo, new RecordItemIndex(0));
            repo.NewScenario.SomeContainer.Scenario_Name.Click(Location.CenterRight);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$scNameEval' with focus on 'NewScenario.SomeContainer.Scenario_Name'.", repo.NewScenario.SomeContainer.Scenario_NameInfo, new RecordItemIndex(1));
            repo.NewScenario.SomeContainer.Scenario_Name.PressKeys(scNameEval);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewScenario.Job_Name' at CenterRight.", repo.NewScenario.Job_NameInfo, new RecordItemIndex(2));
            repo.NewScenario.Job_Name.Click(Location.CenterRight);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$jb4Name' with focus on 'NewScenario.Job_Name'.", repo.NewScenario.Job_NameInfo, new RecordItemIndex(3));
            repo.NewScenario.Job_Name.PressKeys(jb4Name);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewScenario.SomeContainer.Job_Type_Toggle' at 10;16.", repo.NewScenario.SomeContainer.Job_Type_ToggleInfo, new RecordItemIndex(4));
            repo.NewScenario.SomeContainer.Job_Type_Toggle.Click("10;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SkySuiteEasyJetUAT2.Optimization' at 82;11.", repo.SkySuiteEasyJetUAT2.OptimizationInfo, new RecordItemIndex(5));
            repo.SkySuiteEasyJetUAT2.Optimization.Click("82;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewScenario.SomeContainer.Job_Description' at 10;13.", repo.NewScenario.SomeContainer.Job_DescriptionInfo, new RecordItemIndex(6));
            repo.NewScenario.SomeContainer.Job_Description.Click("10;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SkySuiteEasyJetUAT2.Evaluation' at 264;14.", repo.SkySuiteEasyJetUAT2.EvaluationInfo, new RecordItemIndex(7));
            repo.SkySuiteEasyJetUAT2.Evaluation.Click("264;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewScenario.SomeContainer.Job_Dates' at 131;7.", repo.NewScenario.SomeContainer.Job_DatesInfo, new RecordItemIndex(8));
            repo.NewScenario.SomeContainer.Job_Dates.Click("131;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$datesMed' with focus on 'NewScenario.SomeContainer.Job_Dates'.", repo.NewScenario.SomeContainer.Job_DatesInfo, new RecordItemIndex(9));
            repo.NewScenario.SomeContainer.Job_Dates.PressKeys(datesMed);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewScenario.Create' at 49;8.", repo.NewScenario.CreateInfo, new RecordItemIndex(10));
            repo.NewScenario.Create.Click("49;8");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
