///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AtlasAutomation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ImportParameters_4 recording.
    /// </summary>
    [TestModule("508f51ae-64c3-4d83-af45-cf6f6a43647c", ModuleType.Recording, 1)]
    public partial class ImportParameters_4 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the AtlasAutomationRepository repository.
        /// </summary>
        public static AtlasAutomationRepository repo = AtlasAutomationRepository.Instance;

        static ImportParameters_4 instance = new ImportParameters_4();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ImportParameters_4()
        {
            Param_Search_4 = "TC_04_Eval_Med_OPT_Evaluation_Def_Param";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ImportParameters_4 Instance
        {
            get { return instance; }
        }

#region Variables

        string _Param_Search_4;

        /// <summary>
        /// Gets or sets the value of variable Param_Search_4.
        /// </summary>
        [TestVariable("25f19b28-5300-41eb-a5f3-4b2fbc9faf01")]
        public string Param_Search_4
        {
            get { return _Param_Search_4; }
            set { _Param_Search_4 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow.Parameters.Parameter_Toggle' at 40;19.", repo.JobWindow.Parameters.Parameter_ToggleInfo, new RecordItemIndex(0));
            repo.JobWindow.Parameters.Parameter_Toggle.Click("40;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SkySuiteEasyJetUAT2.File' at 23;7.", repo.SkySuiteEasyJetUAT2.FileInfo, new RecordItemIndex(1));
            repo.SkySuiteEasyJetUAT2.File.Click("23;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Open' at 73;802.", repo.Open.SelfInfo, new RecordItemIndex(2));
            repo.Open.Self.Click("73;802");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Open'.", repo.Open.SelfInfo, new RecordItemIndex(3));
            Validate.Exists(repo.Open.SelfInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Open.Documents' at 46;11.", repo.Open.DocumentsInfo, new RecordItemIndex(4));
            repo.Open.Documents.Click("46;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Open.SearchEditBox' at Center.", repo.Open.SearchEditBoxInfo, new RecordItemIndex(5));
            repo.Open.SearchEditBox.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(6));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Param_Search_4' with focus on 'Open'.", repo.Open.SelfInfo, new RecordItemIndex(7));
            repo.Open.Self.EnsureVisible();
            Keyboard.Press(Param_Search_4);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(8));
            Delay.Duration(5000, false);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Open.ExecuteNow' at 26;13.", repo.Open.ExecuteNowInfo, new RecordItemIndex(9));
            //repo.Open.ExecuteNow.Click("26;13");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(10));
            //Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Open.ShellView.TC_04_PreCalibration' at 191;6.", repo.Open.ShellView.TC_04_PreCalibrationInfo, new RecordItemIndex(11));
            repo.Open.ShellView.TC_04_PreCalibration.Click("191;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Open.ButtonOpen' at 73;21.", repo.Open.ButtonOpenInfo, new RecordItemIndex(12));
            repo.Open.ButtonOpen.Click("73;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ImportParameters' at 373;186.", repo.ImportParameters.SelfInfo, new RecordItemIndex(13));
            repo.ImportParameters.Self.Click("373;186");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ImportParameters'.", repo.ImportParameters.SelfInfo, new RecordItemIndex(14));
            Validate.Exists(repo.ImportParameters.SelfInfo);
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.ImportParameters.Self, false, new RecordItemIndex(15));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ImportParameters.ButtonOK' at 4;15.", repo.ImportParameters.ButtonOKInfo, new RecordItemIndex(16));
            repo.ImportParameters.ButtonOK.Click("4;15");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
