///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AtlasAutomation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InputCalibrationDemand2 recording.
    /// </summary>
    [TestModule("d1847639-8828-4eb5-94b2-54eec5fa9880", ModuleType.Recording, 1)]
    public partial class InputCalibrationDemand2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the AtlasAutomationRepository repository.
        /// </summary>
        public static AtlasAutomationRepository repo = AtlasAutomationRepository.Instance;

        static InputCalibrationDemand2 instance = new InputCalibrationDemand2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InputCalibrationDemand2()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InputCalibrationDemand2 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow.TC_01.Alliance_Toggle' at 13;19.", repo.JobWindow.TC_01.Alliance_ToggleInfo, new RecordItemIndex(0));
            repo.JobWindow.TC_01.Alliance_Toggle.Click("13;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(1));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SkySuiteEasyJetUAT2.A1GlobalAlliance' at 61;11.", repo.SkySuiteEasyJetUAT2.A1GlobalAllianceInfo, new RecordItemIndex(2));
            repo.SkySuiteEasyJetUAT2.A1GlobalAlliance.Click("61;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(3));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow.TC_01.Codeshare_Toggle' at 13;13.", repo.JobWindow.TC_01.Codeshare_ToggleInfo, new RecordItemIndex(4));
            repo.JobWindow.TC_01.Codeshare_Toggle.Click("13;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(5));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SkySuiteEasyJetUAT2.A1GlobalCodeshare' at 54;10.", repo.SkySuiteEasyJetUAT2.A1GlobalCodeshareInfo, new RecordItemIndex(6));
            repo.SkySuiteEasyJetUAT2.A1GlobalCodeshare.Click("54;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(7));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow.TC_01.Elapsed_Time_Toggle' at 14;16.", repo.JobWindow.TC_01.Elapsed_Time_ToggleInfo, new RecordItemIndex(8));
            repo.JobWindow.TC_01.Elapsed_Time_Toggle.Click("14;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(9));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SkySuiteEasyJetUAT2.A1GlobalElapsedTime' at 63;9.", repo.SkySuiteEasyJetUAT2.A1GlobalElapsedTimeInfo, new RecordItemIndex(10));
            repo.SkySuiteEasyJetUAT2.A1GlobalElapsedTime.Click("63;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(11));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow.TC_01.Non_Stop_Impact' at 13;18.", repo.JobWindow.TC_01.Non_Stop_ImpactInfo, new RecordItemIndex(12));
            repo.JobWindow.TC_01.Non_Stop_Impact.Click("13;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(13));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SkySuiteEasyJetUAT2.A1GlobalNonStopImpact' at 57;14.", repo.SkySuiteEasyJetUAT2.A1GlobalNonStopImpactInfo, new RecordItemIndex(14));
            repo.SkySuiteEasyJetUAT2.A1GlobalNonStopImpact.Click("57;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(15));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow.TC_01.Partnership_Factor_Toggle' at 9;14.", repo.JobWindow.TC_01.Partnership_Factor_ToggleInfo, new RecordItemIndex(16));
            repo.JobWindow.TC_01.Partnership_Factor_Toggle.Click("9;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(17));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SkySuiteEasyJetUAT2.A1GlobalPartnershipFactor' at 43;19.", repo.SkySuiteEasyJetUAT2.A1GlobalPartnershipFactorInfo, new RecordItemIndex(18));
            repo.SkySuiteEasyJetUAT2.A1GlobalPartnershipFactor.Click("43;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(19));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow.TC_01.Relative_Fare' at 13;14.", repo.JobWindow.TC_01.Relative_FareInfo, new RecordItemIndex(20));
            repo.JobWindow.TC_01.Relative_Fare.Click("13;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(21));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SkySuiteEasyJetUAT2.A1GlobalRelativeFare' at Center.", repo.SkySuiteEasyJetUAT2.A1GlobalRelativeFareInfo, new RecordItemIndex(22));
            repo.SkySuiteEasyJetUAT2.A1GlobalRelativeFare.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(23));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow.TC_01.Service_Type' at 17;18.", repo.JobWindow.TC_01.Service_TypeInfo, new RecordItemIndex(24));
            repo.JobWindow.TC_01.Service_Type.Click("17;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(25));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SkySuiteEasyJetUAT2.A1GlobalServiceType' at 61;9.", repo.SkySuiteEasyJetUAT2.A1GlobalServiceTypeInfo, new RecordItemIndex(26));
            repo.SkySuiteEasyJetUAT2.A1GlobalServiceType.Click("61;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(27));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow.TC_01.Global_Time_of_the_Week_Toggle' at Center.", repo.JobWindow.TC_01.Global_Time_of_the_Week_ToggleInfo, new RecordItemIndex(28));
            repo.JobWindow.TC_01.Global_Time_of_the_Week_Toggle.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(29));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SkySuiteEasyJetUAT2.A1GlobalTimeOfWeekProbCurveParent' at 99;10.", repo.SkySuiteEasyJetUAT2.A1GlobalTimeOfWeekProbCurveParentInfo, new RecordItemIndex(30));
            repo.SkySuiteEasyJetUAT2.A1GlobalTimeOfWeekProbCurveParent.Click("99;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(31));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow.TC_01.Calibration_Demand_Collapse' at Center.", repo.JobWindow.TC_01.Calibration_Demand_CollapseInfo, new RecordItemIndex(32));
            repo.JobWindow.TC_01.Calibration_Demand_Collapse.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(33));
            Delay.Duration(2000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
