///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AtlasAutomation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InputRevenue recording.
    /// </summary>
    [TestModule("dcf04c9c-e63e-448d-bb92-a92fdebef4e8", ModuleType.Recording, 1)]
    public partial class InputRevenue : ITestModule
    {
        /// <summary>
        /// Holds an instance of the AtlasAutomationRepository repository.
        /// </summary>
        public static AtlasAutomationRepository repo = AtlasAutomationRepository.Instance;

        static InputRevenue instance = new InputRevenue();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InputRevenue()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InputRevenue Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable JbWindow_Title.
        /// </summary>
        [TestVariable("adf59c56-3149-4ee6-bffd-8a261f7a9b4c")]
        public string JbWindow_Title
        {
            get { return repo.JbWindow_Title; }
            set { repo.JbWindow_Title = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow1.SomeContainer.Revenue_Expand' at 6;10.", repo.JobWindow1.SomeContainer.Revenue_ExpandInfo, new RecordItemIndex(0));
            repo.JobWindow1.SomeContainer.Revenue_Expand.Click("6;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(1));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow1.SomeContainer.Relative_Fare_by_Week_Toggle' at Center.", repo.JobWindow1.SomeContainer.Relative_Fare_by_Week_ToggleInfo, new RecordItemIndex(2));
            repo.JobWindow1.SomeContainer.Relative_Fare_by_Week_Toggle.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(3));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SkySuiteEasyJetUAT2.A1GlobalRelativeFareByTimeOfWeek' at 51;18.", repo.SkySuiteEasyJetUAT2.A1GlobalRelativeFareByTimeOfWeekInfo, new RecordItemIndex(4));
            repo.SkySuiteEasyJetUAT2.A1GlobalRelativeFareByTimeOfWeek.Click("51;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(5));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow1.SomeContainer.Revenue_Toggle' at Center.", repo.JobWindow1.SomeContainer.Revenue_ToggleInfo, new RecordItemIndex(6));
            repo.JobWindow1.SomeContainer.Revenue_Toggle.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(7));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SkySuiteEasyJetUAT2.A1GlobalProrate' at 50;6.", repo.SkySuiteEasyJetUAT2.A1GlobalProrateInfo, new RecordItemIndex(8));
            repo.SkySuiteEasyJetUAT2.A1GlobalProrate.Click("50;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(9));
            Delay.Duration(1000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
