///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AtlasAutomation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InputCalibrationNetwork recording.
    /// </summary>
    [TestModule("65362fe7-7bec-4482-a07e-fd36e97d9999", ModuleType.Recording, 1)]
    public partial class InputCalibrationNetwork : ITestModule
    {
        /// <summary>
        /// Holds an instance of the AtlasAutomationRepository repository.
        /// </summary>
        public static AtlasAutomationRepository repo = AtlasAutomationRepository.Instance;

        static InputCalibrationNetwork instance = new InputCalibrationNetwork();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InputCalibrationNetwork()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InputCalibrationNetwork Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow.TC_01.Calibration_Network_Expand' at Center.", repo.JobWindow.TC_01.Calibration_Network_ExpandInfo, new RecordItemIndex(0));
            repo.JobWindow.TC_01.Calibration_Network_Expand.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(1));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow.TC_01.Circuity_Toggle' at Center.", repo.JobWindow.TC_01.Circuity_ToggleInfo, new RecordItemIndex(2));
            repo.JobWindow.TC_01.Circuity_Toggle.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(3));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SkySuiteEasyJetUAT2.A1GlobalCombinedCircuity' at 73;9.", repo.SkySuiteEasyJetUAT2.A1GlobalCombinedCircuityInfo, new RecordItemIndex(4));
            repo.SkySuiteEasyJetUAT2.A1GlobalCombinedCircuity.Click("73;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(5));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow.TC_01.Duplicate_Rule_Toggle' at Center.", repo.JobWindow.TC_01.Duplicate_Rule_ToggleInfo, new RecordItemIndex(6));
            repo.JobWindow.TC_01.Duplicate_Rule_Toggle.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(7));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SkySuiteEasyJetUAT2.A1GlobalDuplicateRule' at 57;12.", repo.SkySuiteEasyJetUAT2.A1GlobalDuplicateRuleInfo, new RecordItemIndex(8));
            repo.SkySuiteEasyJetUAT2.A1GlobalDuplicateRule.Click("57;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(9));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow.TC_01.Combined_Pruning_Toggle' at 13;16.", repo.JobWindow.TC_01.Combined_Pruning_ToggleInfo, new RecordItemIndex(10));
            repo.JobWindow.TC_01.Combined_Pruning_Toggle.Click("13;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(11));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SkySuiteEasyJetUAT2.A1GlobalCombinedPruning' at 69;12.", repo.SkySuiteEasyJetUAT2.A1GlobalCombinedPruningInfo, new RecordItemIndex(12));
            repo.SkySuiteEasyJetUAT2.A1GlobalCombinedPruning.Click("69;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(13));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow.TC_01.Combined_Suppression_Toggle' at 10;9.", repo.JobWindow.TC_01.Combined_Suppression_ToggleInfo, new RecordItemIndex(14));
            repo.JobWindow.TC_01.Combined_Suppression_Toggle.Click("10;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(15));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SkySuiteEasyJetUAT2.A1GlobalCombinedSuppression' at 26;14.", repo.SkySuiteEasyJetUAT2.A1GlobalCombinedSuppressionInfo, new RecordItemIndex(16));
            repo.SkySuiteEasyJetUAT2.A1GlobalCombinedSuppression.Click("26;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(17));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow.TC_01.Calibration_Network_Collapse' at Center.", repo.JobWindow.TC_01.Calibration_Network_CollapseInfo, new RecordItemIndex(18));
            repo.JobWindow.TC_01.Calibration_Network_Collapse.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(19));
            Delay.Duration(1000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
