///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AtlasAutomation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InputSchedule recording.
    /// </summary>
    [TestModule("a21464cf-05dc-4b78-b531-54fb8162eefa", ModuleType.Recording, 1)]
    public partial class InputSchedule : ITestModule
    {
        /// <summary>
        /// Holds an instance of the AtlasAutomationRepository repository.
        /// </summary>
        public static AtlasAutomationRepository repo = AtlasAutomationRepository.Instance;

        static InputSchedule instance = new InputSchedule();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InputSchedule()
        {
            Dates_Med = "18Sep2023 to 24Sep2023";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InputSchedule Instance
        {
            get { return instance; }
        }

#region Variables

        string _Dates_Med;

        /// <summary>
        /// Gets or sets the value of variable Dates_Med.
        /// </summary>
        [TestVariable("0b2e0f63-89dc-44cf-aaaf-34c6bfbb9921")]
        public string Dates_Med
        {
            get { return _Dates_Med; }
            set { _Dates_Med = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable JbWindow_Title.
        /// </summary>
        [TestVariable("adf59c56-3149-4ee6-bffd-8a261f7a9b4c")]
        public string JbWindow_Title
        {
            get { return repo.JbWindow_Title; }
            set { repo.JbWindow_Title = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow1.SomeContainer.Schedule_Expand' at Center.", repo.JobWindow1.SomeContainer.Schedule_ExpandInfo, new RecordItemIndex(0));
            repo.JobWindow1.SomeContainer.Schedule_Expand.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(1));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow1.SomeContainer.OA_Toggle' at Center.", repo.JobWindow1.SomeContainer.OA_ToggleInfo, new RecordItemIndex(2));
            repo.JobWindow1.SomeContainer.OA_Toggle.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(3));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SomeContextMenu.S23AmadeusSampleNew' at 45;12.", repo.SomeContextMenu.S23AmadeusSampleNewInfo, new RecordItemIndex(4));
            repo.SomeContextMenu.S23AmadeusSampleNew.Click("45;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(5));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow1.SomeContainer.OA_Dates' at 58;12.", repo.JobWindow1.SomeContainer.OA_DatesInfo, new RecordItemIndex(6));
            repo.JobWindow1.SomeContainer.OA_Dates.Click("58;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Dates_Med' with focus on 'JobWindow1.SomeContainer.OA_Dates'.", repo.JobWindow1.SomeContainer.OA_DatesInfo, new RecordItemIndex(7));
            repo.JobWindow1.SomeContainer.OA_Dates.PressKeys(Dates_Med);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow1.SomeContainer.Replacement_Toggle' at 7;14.", repo.JobWindow1.SomeContainer.Replacement_ToggleInfo, new RecordItemIndex(8));
            repo.JobWindow1.SomeContainer.Replacement_Toggle.Click("7;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(9));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SomeContextMenu.S23AmadeusSampleNew' at 66;13.", repo.SomeContextMenu.S23AmadeusSampleNewInfo, new RecordItemIndex(10));
            repo.SomeContextMenu.S23AmadeusSampleNew.Click("66;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(11));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow1.SomeContainer.Replacement_Dates' at 19;11.", repo.JobWindow1.SomeContainer.Replacement_DatesInfo, new RecordItemIndex(12));
            repo.JobWindow1.SomeContainer.Replacement_Dates.Click("19;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Dates_Med' with focus on 'JobWindow1.SomeContainer.Replacement_Dates'.", repo.JobWindow1.SomeContainer.Replacement_DatesInfo, new RecordItemIndex(13));
            repo.JobWindow1.SomeContainer.Replacement_Dates.PressKeys(Dates_Med);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(14));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow1.SomeContainer.Schedule_Expand' at 21;17.", repo.JobWindow1.SomeContainer.Schedule_ExpandInfo, new RecordItemIndex(15));
            repo.JobWindow1.SomeContainer.Schedule_Expand.Click("21;17");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(16));
            Delay.Duration(1000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
