///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AtlasAutomation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InputParameters04 recording.
    /// </summary>
    [TestModule("a301c1cb-8721-4f16-bf30-30aa700f7a9e", ModuleType.Recording, 1)]
    public partial class InputParameters04 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the AtlasAutomationRepository repository.
        /// </summary>
        public static AtlasAutomationRepository repo = AtlasAutomationRepository.Instance;

        static InputParameters04 instance = new InputParameters04();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InputParameters04()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InputParameters04 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow.TC_04.Parameters_Expand' at Center.", repo.JobWindow.TC_04.Parameters_ExpandInfo, new RecordItemIndex(0));
            repo.JobWindow.TC_04.Parameters_Expand.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 100ms.", new RecordItemIndex(1));
            Delay.Duration(100, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow.TC_04.Optimisation_Parameters' at 10;15.", repo.JobWindow.TC_04.Optimisation_ParametersInfo, new RecordItemIndex(2));
            repo.JobWindow.TC_04.Optimisation_Parameters.Click("10;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 100ms.", new RecordItemIndex(3));
            Delay.Duration(100, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SkySuiteEasyJetUAT2.S23MASTEROptimizationParametersPreUA' at 218;19.", repo.SkySuiteEasyJetUAT2.S23MASTEROptimizationParametersPreUAInfo, new RecordItemIndex(4));
            repo.SkySuiteEasyJetUAT2.S23MASTEROptimizationParametersPreUA.Click("218;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 100ms.", new RecordItemIndex(5));
            Delay.Duration(100, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow.TC_04.Optimisation_Configuration' at Center.", repo.JobWindow.TC_04.Optimisation_ConfigurationInfo, new RecordItemIndex(6));
            repo.JobWindow.TC_04.Optimisation_Configuration.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 100ms.", new RecordItemIndex(7));
            Delay.Duration(100, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SkySuiteEasyJetUAT2.S23MASTERClientConfigPreUATV2' at Center.", repo.SkySuiteEasyJetUAT2.S23MASTERClientConfigPreUATV2Info, new RecordItemIndex(8));
            repo.SkySuiteEasyJetUAT2.S23MASTERClientConfigPreUATV2.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 100ms.", new RecordItemIndex(9));
            Delay.Duration(100, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
