///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AtlasAutomation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ModifySchedule recording.
    /// </summary>
    [TestModule("23712307-9086-4c4d-be22-c2f97e54d5e4", ModuleType.Recording, 1)]
    public partial class ModifySchedule : ITestModule
    {
        /// <summary>
        /// Holds an instance of the AtlasAutomationRepository repository.
        /// </summary>
        public static AtlasAutomationRepository repo = AtlasAutomationRepository.Instance;

        static ModifySchedule instance = new ModifySchedule();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ModifySchedule()
        {
            datesPeak = "21Aug2023 to 27Aug2023";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ModifySchedule Instance
        {
            get { return instance; }
        }

#region Variables

        string _datesPeak;

        /// <summary>
        /// Gets or sets the value of variable datesPeak.
        /// </summary>
        [TestVariable("d46d5f03-393d-457f-b71c-23f0481a1446")]
        public string datesPeak
        {
            get { return _datesPeak; }
            set { _datesPeak = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow.Job_Inputs.JobInputsBusyIndicator' at 684;36.", repo.JobWindow.Job_Inputs.JobInputsBusyIndicatorInfo, new RecordItemIndex(0));
            repo.JobWindow.Job_Inputs.JobInputsBusyIndicator.Click("684;36");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow.Job_Inputs.Schedule_Expand' at 22;16.", repo.JobWindow.Job_Inputs.Schedule_ExpandInfo, new RecordItemIndex(1));
            repo.JobWindow.Job_Inputs.Schedule_Expand.Click("22;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow.TC_02.OA_Dates' at 76;16.", repo.JobWindow.TC_02.OA_DatesInfo, new RecordItemIndex(2));
            repo.JobWindow.TC_02.OA_Dates.Click("76;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$datesPeak' with focus on 'JobWindow.TC_02.OA_Dates'.", repo.JobWindow.TC_02.OA_DatesInfo, new RecordItemIndex(3));
            repo.JobWindow.TC_02.OA_Dates.PressKeys(datesPeak);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow.TC_02.Replacement_Dates' at 112;4.", repo.JobWindow.TC_02.Replacement_DatesInfo, new RecordItemIndex(4));
            repo.JobWindow.TC_02.Replacement_Dates.Click("112;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$datesPeak' with focus on 'JobWindow.TC_02.Replacement_Dates'.", repo.JobWindow.TC_02.Replacement_DatesInfo, new RecordItemIndex(5));
            repo.JobWindow.TC_02.Replacement_Dates.PressKeys(datesPeak);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow.Job_Inputs.Schedule_Expand' at 22;16.", repo.JobWindow.Job_Inputs.Schedule_ExpandInfo, new RecordItemIndex(6));
            repo.JobWindow.Job_Inputs.Schedule_Expand.Click("22;16");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
