///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AtlasAutomation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ModifyBuild___TC5 recording.
    /// </summary>
    [TestModule("2c6de8ba-2b5d-4267-8c96-cfe093ee7830", ModuleType.Recording, 1)]
    public partial class ModifyBuild___TC5 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the AtlasAutomationRepository repository.
        /// </summary>
        public static AtlasAutomationRepository repo = AtlasAutomationRepository.Instance;

        static ModifyBuild___TC5 instance = new ModifyBuild___TC5();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ModifyBuild___TC5()
        {
            datesPeak = "21Aug2023 to 27Aug2023";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ModifyBuild___TC5 Instance
        {
            get { return instance; }
        }

#region Variables

        string _datesPeak;

        /// <summary>
        /// Gets or sets the value of variable datesPeak.
        /// </summary>
        [TestVariable("f3c9faa2-0884-4ba8-b2fe-b32398eb81bf")]
        public string datesPeak
        {
            get { return _datesPeak; }
            set { _datesPeak = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow.Job_Details.Import_Build_Toggle' at 14;5.", repo.JobWindow.Job_Details.Import_Build_ToggleInfo, new RecordItemIndex(0));
            repo.JobWindow.Job_Details.Import_Build_Toggle.Click("14;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SkySuiteEasyJetUAT2.TC02PreCalibrationIBPeak' at 263;15.", repo.SkySuiteEasyJetUAT2.TC02PreCalibrationIBPeakInfo, new RecordItemIndex(1));
            repo.SkySuiteEasyJetUAT2.TC02PreCalibrationIBPeak.Click("263;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobWindow.Job_Details.Planning_Period' at 159;10.", repo.JobWindow.Job_Details.Planning_PeriodInfo, new RecordItemIndex(2));
            repo.JobWindow.Job_Details.Planning_Period.Click("159;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$datesPeak' with focus on 'JobWindow.Job_Details.Planning_Period'.", repo.JobWindow.Job_Details.Planning_PeriodInfo, new RecordItemIndex(3));
            repo.JobWindow.Job_Details.Planning_Period.PressKeys(datesPeak);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
