
name: Ranorex Run

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: [self-hosted, Windows]


    steps:

      - uses: actions/checkout@v3

      - name: Cd
        run: cd "D:"

      - name: ls
        run: ls 
        

        
