
name: Ranorex Run

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: [self-hosted, Windows]


    steps:

      - uses: actions/checkout@v3

      - name: Cd
        run: cd "D:\Users\CatherineB\Documents\Ranorex\RanorexStudio Projects\Atlas-Automation-main\AtlasAutomation\bin\Debug"

      - name: ls
        run: ls 
        

        
